version: "3"

services:
  app:
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/app/src"
      - "yarn-cache:/root/.cache/yarn"
      - "app-node-modules:/usr/app/src/node_modules"
    ports:
      - "3000:3000"
    links:
      - postgres
      - memcached

  postgres:
    image: postgres:9-alpine
    container_name: postgresdb
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432"
    environment:
     - POSTGRES_USER=demo
     - POSTGRES_PASSWORD=demo
     - POSTGRES_DB=demodb

  memcached:
    image: memcached:1.4-alpine
    container_name: memcached

volumes:
  yarn-cache:
  postgres:
  app-node-modules:

